"use client";

import { useEffect, useState } from "react";
import { Bell, ChevronRight, CircleHelp, Copy, Gift, Home, ListChecks, Share2, ShieldCheck, Sparkles, UserRound, Users, WalletCards, Zap, ArrowDownToLine, ArrowUpFromLine, ArrowLeftRight, Play, Pause, CheckCircle2, TrendingUp, BarChart3, Menu } from "lucide-react";

type Tab = "home" | "mine" | "tasks" | "wallet" | "profile";
const SPEED=0.00124;
const APP_URL="https://pointpro-one.vercel.app";
const REFERRAL="PPUSER";

export default function PointProApp(){
 const [tab,setTab]=useState<Tab>("home"),[balance,setBalance]=useState(0),[today,setToday]=useState(0),[mining,setMining]=useState(true),[boost,setBoost]=useState(false),[toast,setToast]=useState("");
 const speed=boost?SPEED*1.2:SPEED;
 useEffect(()=>{if(!mining)return;const id=window.setInterval(()=>{setBalance(v=>v+speed);setToday(v=>v+speed)},1000);return()=>clearInterval(id)},[mining,speed]);
 useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(""),2200);return()=>clearTimeout(id)},[toast]);
 const notify=(s:string)=>setToast(s), progress=Math.min(100,Math.round(today/(SPEED*86400)*100));
 const copy=async()=>{try{await navigator.clipboard.writeText(`${APP_URL}/?ref=${REFERRAL}`);notify("Referral link copied")}catch{notify("Copy failed")}};
 const share=async()=>{const url=`${APP_URL}/?ref=${REFERRAL}`;if(navigator.share)await navigator.share({title:"PointPro",text:"Join PointPro",url});else await copy()};
 return <div className="min-h-screen bg-[#f5f7fb] text-[#18243b]">
  <header className="sticky top-0 z-40 border-b border-[#e5e9f2] bg-white/95 backdrop-blur"><div className="mx-auto flex h-[70px] max-w-[680px] items-center justify-between px-5">
   <div className="flex items-center gap-2"><img src="/pointpro-mark.svg" className="h-9 w-9"/><div className="text-[25px] font-black tracking-[-1.5px]">Point<span className="text-[#25d67c]">Pro</span></div></div>
   <button onClick={()=>notify("Telegram will be connected from your bot settings")} className="flex items-center gap-2 rounded-2xl bg-[#159fe9] px-4 py-2.5 text-sm font-bold text-white shadow-[0_8px_18px_rgba(21,159,233,.2)]">✈ Telegram</button>
  </div></header>
  <main className="mx-auto max-w-[680px] px-4 pb-28 pt-5">
   {tab==="home"&&<Home p={{balance,today,mining,speed,progress,setMining,setTab,notify}}/>}
   {tab==="mine"&&<Mine p={{balance,today,mining,speed,boost,setMining,setBoost,notify}}/>}
   {tab==="tasks"&&<Tasks p={{mining,setMining,share,notify}}/>}
   {tab==="wallet"&&<Wallet p={{balance,today,notify}}/>}
   {tab==="profile"&&<Profile p={{copy,share}}/>}
  </main>
  <nav className="fixed bottom-0 left-0 right-0 z-50 border-t border-[#e3e8f1] bg-white/98 backdrop-blur"><div className="mx-auto grid max-w-[680px] grid-cols-5">
   {([["home",Home,"Home"],["mine",Zap,"Mine"],["tasks",ListChecks,"Tasks"],["wallet",WalletCards,"Wallet"],["profile",UserRound,"Profile"]] as const).map(([k,I,l])=><button key={k} onClick={()=>setTab(k)} className={`flex flex-col items-center gap-1 py-2.5 text-[11px] font-semibold ${tab===k?"text-[#2868ed]":"text-[#8993a6]"}`}><I size={22} strokeWidth={tab===k?2.5:2}/><span>{l}</span></button>)}
  </div></nav>
  {toast&&<div className="fixed bottom-24 left-1/2 z-[60] -translate-x-1/2 rounded-2xl bg-[#18243b] px-4 py-3 text-sm font-semibold text-white shadow-xl">{toast}</div>}
 </div>
}

function Home({p}:any){return <div className="space-y-5">
 <div className="flex items-start justify-between"><div><p className="text-[15px] text-[#8993a6]">Welcome back 👋</p><h1 className="mt-1 text-[30px] font-black tracking-tight">My Dashboard</h1></div><button onClick={()=>p.notify("No new notifications")} className="rounded-full bg-white p-3 shadow-[0_8px_25px_rgba(31,51,86,.09)]"><Bell size={20}/></button></div>
 <section className="relative overflow-hidden rounded-[28px] bg-gradient-to-br from-[#2f70f4] to-[#1850cf] p-6 text-white shadow-[0_18px_38px_rgba(47,112,244,.22)]"><div className="absolute right-0 top-0 opacity-20"><img src="/pp-coin-stack.svg" className="w-48"/></div>
  <p className="relative text-sm font-semibold text-blue-100">PP Coin Balance</p><div className="relative mt-2 text-[39px] font-black">{p.balance.toFixed(6)} <span className="text-lg text-blue-100">PP</span></div><p className="relative text-sm text-blue-100">≈ $0.00 USD • Live Rate</p>
  <div className="relative mt-6 grid grid-cols-2 gap-3"><Mini title="Today's Earnings" value={p.today.toFixed(4)+" PP"}/><Mini title="Mining Speed" value={"+"+p.speed.toFixed(5)+"/sec"}/></div>
 </section>
 <section className="rounded-[28px] bg-white p-5 shadow-[0_12px_30px_rgba(31,51,86,.08)]"><div className="flex items-center justify-between"><h2 className="text-[21px] font-black">Mining Status</h2><span className={`rounded-full px-3 py-1 text-xs font-bold ${p.mining?"bg-[#e8fff3] text-[#20b96c]":"bg-[#f0f2f6] text-[#8993a6]"}`}>{p.mining?"● Active":"Paused"}</span></div>
  <div className="my-6 flex items-center gap-5"><div className="relative grid h-32 w-32 shrink-0 place-items-center rounded-full" style={{background:`conic-gradient(#2f70f4 ${Math.max(4,p.progress)}%,#e8edf5 0)`}}><div className="grid h-24 w-24 place-items-center rounded-full bg-white text-center"><Zap className="text-[#2f70f4]" size={25}/><b className="text-lg">{p.balance.toFixed(3)}</b><small className="text-[10px] text-[#8993a6]">PP COIN</small></div></div><div className="flex-1"><p className="text-sm text-[#8993a6]">Mining Rate</p><b className="text-2xl">+{p.speed.toFixed(5)} PP/s</b><p className="mt-2 text-xs text-[#8993a6]">24H Progress • {p.progress}%</p></div></div>
  <div className="h-2 overflow-hidden rounded-full bg-[#e8edf5]"><div className="h-full rounded-full bg-[#2f70f4]" style={{width:`${Math.max(3,p.progress)}%`}}/></div>
  <button onClick={()=>p.setMining((v:boolean)=>!v)} className="mt-4 flex w-full items-center justify-center gap-2 rounded-2xl bg-[#2f70f4] py-3.5 font-bold text-white shadow-[0_10px_20px_rgba(47,112,244,.2)]">{p.mining?<><Pause size={17}/> Pause Mining</>:<><Play size={17}/> Start Mining</>}</button>
 </section>
 <div className="grid grid-cols-4 gap-2.5"><Quick icon={<Gift/>} label="Daily" onClick={()=>p.notify("Daily reward is ready")}/><Quick icon={<Zap/>} label="Boost" onClick={()=>p.setTab("mine")}/><Quick icon={<ListChecks/>} label="Tasks" onClick={()=>p.setTab("tasks")}/><Quick icon={<Users/>} label="Invite" onClick={()=>p.setTab("profile")}/></div>
 <section className="rounded-[26px] bg-white p-5 shadow-[0_10px_28px_rgba(31,51,86,.07)]"><div className="flex items-center justify-between"><h2 className="text-xl font-black">Live Mining Widget</h2><TrendingUp className="text-[#25d67c]"/></div><div className="mt-4 flex h-20 items-end gap-1">{[35,48,42,65,52,78,61,88,70,94,76,100].map((h,i)=><div key={i} className="flex-1 rounded-t bg-[#2f70f4]/20" style={{height:`${h}%`}}><div className="h-full w-full rounded-t bg-[#2f70f4]/60"/></div>)}</div><div className="mt-3 flex justify-between text-xs text-[#8993a6]"><span>Now</span><b className="text-[#25b978]">+{p.speed.toFixed(5)} PP/s</b><span>24h</span></div></section>
 </div>}

function Mine({p}:any){return <div className="space-y-5"><Title title="Mine PP Coin" sub="Your mining control center"/><section className="relative overflow-hidden rounded-[28px] bg-gradient-to-br from-[#2f70f4] to-[#194fc9] p-6 text-white"><img src="/pp-coin-stack.svg" className="absolute -right-6 bottom-0 w-44 opacity-90"/><p className="text-sm text-blue-100">PP Coin Balance</p><b className="mt-1 block text-4xl">{p.balance.toFixed(6)} PP</b><p className="mt-6 text-sm text-blue-100">Mining power</p><b className="text-xl">+{p.speed.toFixed(5)} PP / sec</b></section><Card title="Mining Statistics"><Row a="Per minute" b={`+${(p.speed*60).toFixed(4)} PP`}/><Row a="Per hour" b={`+${(p.speed*3600).toFixed(2)} PP`}/><Row a="Per day" b={`+${(p.speed*86400).toFixed(2)} PP`}/><Row a="Mining status" b={p.mining?"Active":"Paused"}/></Card><Card title="Boost Center"><Boost name="Energy Boost" value="+10%" active={p.boost} onClick={()=>p.setBoost(true)}/><Boost name="Super Boost" value="+20%" active={p.boost} onClick={()=>p.setBoost(true)}/></Card></div>}

function Tasks({p}:any){return <div className="space-y-5"><Title title="Tasks" sub="Complete tasks and earn more PP Coin."/><div className="flex gap-2 overflow-x-auto pb-1">{["Watch Ads","Daily Tasks","Social Tasks","Special"].map((x,i)=><span key={x} className={`whitespace-nowrap rounded-full border px-5 py-2.5 text-sm font-bold ${i===0?"border-[#2f70f4] bg-[#2f70f4] text-white":"border-[#e4e8f0] bg-white text-[#8993a6]"}`}>{x}</span>)}</div><Card><Task icon={<Gift/>} title="Daily Check-in" text="Claim your daily reward" button="+5 PP" onClick={()=>p.notify("+5 PP reward claimed")}/><Task icon={<Zap/>} title="Mining Session" text="Keep your miner active" button={p.mining?"Active":"Start"} onClick={()=>p.setMining((v:boolean)=>!v)}/><Task icon={<Users/>} title="Invite a Friend" text="Share your PointPro referral link" button="Invite" onClick={p.share}/><Task icon={<Sparkles/>} title="Community Task" text="Connect with the PointPro community" button="Open" onClick={()=>p.notify("Community task coming soon")}/></Card></div>}

function Wallet({p}:any){return <div className="space-y-5"><Title title="Wallet" sub="Manage your PP Coin securely."/><section className="relative overflow-hidden rounded-[28px] bg-gradient-to-br from-[#2f70f4] to-[#174bc8] p-6 text-white shadow-[0_15px_35px_rgba(47,112,244,.2)]"><p className="text-sm font-bold text-blue-100">POINTPRO WALLET</p><b className="mt-2 block text-4xl">{p.balance.toFixed(6)} PP</b><p className="mt-1 text-sm text-blue-100">≈ $0.00 USD • Live Rate</p><div className="mt-6 grid grid-cols-3 gap-2 text-center text-xs"><div><b className="block text-base">{p.balance.toFixed(3)}</b>Total</div><div><b className="block text-base">{p.today.toFixed(3)}</b>Today</div><div><b className="block text-base">0</b>Transactions</div></div></section><div className="grid grid-cols-4 gap-2.5"><WalletAction icon={<ArrowDownToLine/>} label="Receive" onClick={()=>p.notify("Receive address will be connected")}/><WalletAction icon={<ArrowUpFromLine/>} label="Send" onClick={()=>p.notify("Send module ready for Supabase")}/><WalletAction icon={<ArrowLeftRight/>} label="Exchange" onClick={()=>p.notify("Exchange module coming soon")}/><WalletAction icon={<ArrowUpFromLine/>} label="Withdraw" onClick={()=>p.notify("Withdrawal module coming soon")}/></div><Card title="Recent Transactions"><div className="rounded-2xl bg-[#f5f7fb] p-6 text-center text-sm text-[#8993a6]">No transactions yet</div></Card></div>}

function Profile({p}:any){return <div className="space-y-5"><Title title="Profile" sub="Your PointPro account"/><section className="rounded-[28px] bg-white p-5 shadow-[0_12px_30px_rgba(31,51,86,.08)]"><div className="flex items-center gap-4"><div className="grid h-16 w-16 place-items-center rounded-full bg-[#eaf2ff]"><UserRound size={31} className="text-[#2f70f4]"/></div><div><h2 className="text-xl font-black">PointPro Miner</h2><p className="text-sm text-[#8993a6]">@ppuser</p></div><CheckCircle2 className="ml-auto text-[#25c879]"/></div><div className="mt-5 rounded-2xl bg-[#101a29] p-4 text-white"><p className="text-xs text-slate-400">Your Referral Code</p><b className="mt-1 block text-2xl text-[#ffd02f]">{REFERRAL}</b><p className="mt-2 text-sm text-slate-400">Invite friends and earn referral rewards.</p></div></section><Card title="Referral"><Row a="Referral code" b={REFERRAL}/><Row a="Total referrals" b="0"/><Row a="Referral earnings" b="0.000000 PP"/><div className="mt-3 flex gap-2"><button onClick={p.copy} className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-[#2f70f4] py-3 font-bold text-white"><Copy size={16}/> Copy</button><button onClick={p.share} className="flex flex-1 items-center justify-center gap-2 rounded-xl border border-[#e3e8f1] py-3 font-bold"><Share2 size={16}/> Share</button></div></Card><Card><MenuRow icon={<ShieldCheck/>} text="Security"/><MenuRow icon={<Bell/>} text="Notifications"/><MenuRow icon={<CircleHelp/>} text="Support"/></Card></div>}

function Title({title,sub}:{title:string;sub:string}){return <div><h1 className="text-[30px] font-black tracking-tight">{title}</h1><p className="mt-1 text-sm text-[#8993a6]">{sub}</p></div>}
function Mini({title,value}:{title:string;value:string}){return <div className="rounded-2xl bg-white/10 p-3 backdrop-blur"><small className="text-xs text-blue-100">{title}</small><b className="mt-1 block text-sm">{value}</b></div>}
function Quick({icon,label,onClick}:any){return <button onClick={onClick} className="flex flex-col items-center gap-2 rounded-2xl bg-white p-3 text-xs font-bold text-[#556179] shadow-[0_8px_22px_rgba(31,51,86,.07)]">{icon}{label}</button>}
function WalletAction({icon,label,onClick}:any){return <button onClick={onClick} className="flex flex-col items-center gap-2 rounded-2xl bg-white p-3 text-[11px] font-bold text-[#556179] shadow-[0_8px_22px_rgba(31,51,86,.07)]">{icon}{label}</button>}
function Card({title,children}:any){return <section className="rounded-[28px] bg-white p-5 shadow-[0_10px_28px_rgba(31,51,86,.07)]">{title&&<h2 className="mb-2 text-[20px] font-black">{title}</h2>}{children}</section>}
function Row({a,b}:{a:string;b:string}){return <div className="flex items-center justify-between border-b border-[#edf0f5] py-3.5 text-sm last:border-0"><span className="text-[#8993a6]">{a}</span><b>{b}</b></div>}
function Boost({name,value,active,onClick}:any){return <div className="flex items-center gap-3 border-b border-[#edf0f5] py-3 last:border-0"><div className="rounded-xl bg-[#eaf2ff] p-2.5 text-[#2f70f4]"><Zap size={18}/></div><div className="flex-1"><b>{name}</b><p className="text-xs text-[#8993a6]">Increase mining power</p></div><button onClick={onClick} className={`rounded-xl px-3 py-2 text-xs font-bold ${active?"bg-[#e8fff3] text-[#20b96c]":"bg-[#2f70f4] text-white"}`}>{active?"Active":value}</button></div>}
function Task({icon,title,text,button,onClick}:any){return <div className="flex items-center gap-3 border-b border-[#edf0f5] py-4 last:border-0"><div className="rounded-xl bg-[#eaf2ff] p-3 text-[#2f70f4]">{icon}</div><div className="min-w-0 flex-1"><b className="block text-sm">{title}</b><small className="text-xs text-[#8993a6]">{text}</small></div><button onClick={onClick} className="rounded-xl bg-[#2f70f4] px-3 py-2 text-xs font-bold text-white">{button}</button></div>}
function MenuRow({icon,text}:{icon:any;text:string}){return <button className="flex w-full items-center gap-3 border-b border-[#edf0f5] py-4 text-left last:border-0"><span className="text-[#68758b]">{icon}</span><b className="flex-1 text-sm">{text}</b><ChevronRight size={18} className="text-[#8993a6]"/></button>}
